### ISSUE TITLE
Relative humidity

### ISSUE THREAD

**Issue by BinCAO-PF** [geocryology/globsim#123]
Current globsim derived relative humidity (function: relhu_approx_lawrence in meteorology.py) from Lawrence (https://doi.org/10.1175/BAMS-86-2-225). This works well in Lac de Gras. N.W.T., Canada, but produced artificial results in Tibetan-Plateau. This is because the big difference between dew temperature and near-surface air temperature leads to relative humidity equal to zero. I read the toposcale paper and found the method provided by Liston (http://journals.ametsoc.org/doi/10.1175/JHM486.1) would be a nice alternative. The new relative humidity function also improves scaled downward longwave radiation as a whole.

I just copied the new relative humidity function below

```python
def rh_liston(t: np.ndarray, td: np.ndarray) -> np.ndarray:
    """
    t : temperature [C]
    td : dewpoint temperature [C]
    returns : relative humidity [%]
    """
    t = np.atleast_1d(t)
    td = np.atleast_1d(td)
    
    a = 611.21
    b = 17.502
    c = 240.97
    
    e = a * np.exp(b * td / (c + td))
    es = a * np.exp(b * t / (c + t))
    rh = 100 * e / es
    
    return rh
```

**Comment by nicholas512** [comment]
You can now choose between Liston (default) and Lawrence relative humidity approximations using the rh_approximation parameter in the parameter file.

[scale]
rh_approximation = 'rh_liston'
# rh_approximation = 'rh_lawrence'
