### ISSUE TITLE
JRA-3Q

### ISSUE THREAD

**Issue by nicholas512** [geocryology/globsim#133]

**Comment by nicholas512** [comment]
* download from DIAS - need registration
* seems to be only GRIB files available
* automatically-generated script download seems to differ slightly in UUID for filename
```
    access.dl('https://data.diasjp.net/dl/storages/downloadCmd/L0pSQTNRL0NsaW05MTIwL0RhaWx5L2FubF9pc2VudHJvcDEyNS9hbmxfaXNlbnRyb3AxMjVfYnZmMi5jbGltOTEyMC5kYXkwMTIw', '/JRA3Q/Clim9120/Daily/anl_isentrop125/', 'anl_isentrop125_bvf2.clim9120.day0120')

    access.dl('https://data.diasjp.net/dl/storages/downloadCmd/L0pSQTNRL0NsaW05MTIwL0RhaWx5L2FubF9pc2VudHJvcDEyNS9hbmxfaXNlbnRyb3AxMjVfYnZmMi5jbGltOTEyMC5kYXkwMTIx', '/JRA3Q/Clim9120/Daily/anl_isentrop125/', 'anl_isentrop125_bvf2.clim9120.day0121')
```

**Comment by BinCAO-PF** [comment]
seems to be only GRIB files availableYes, nc file does not available for now.automatically-generated script download seems to differ slightly in UUID for filenameThe script is for Python2.7, only.在 2023年8月16日，02:30，Nick ***@***.***> 写道：﻿

download from DIAS - need registration
seems to be only GRIB files available
automatically-generated script download seems to differ slightly in UUID for filename

    access.dl('https://data.diasjp.net/dl/storages/downloadCmd/L0pSQTNRL0NsaW05MTIwL0RhaWx5L2FubF9pc2VudHJvcDEyNS9hbmxfaXNlbnRyb3AxMjVfYnZmMi5jbGltOTEyMC5kYXkwMTIw', '/JRA3Q/Clim9120/Daily/anl_isentrop125/', 'anl_isentrop125_bvf2.clim9120.day0120')

    access.dl('https://data.diasjp.net/dl/storages/downloadCmd/L0pSQTNRL0NsaW05MTIwL0RhaWx5L2FubF9pc2VudHJvcDEyNS9hbmxfaXNlbnRyb3AxMjVfYnZmMi5jbGltOTEyMC5kYXkwMTIx', '/JRA3Q/Clim9120/Daily/anl_isentrop125/', 'anl_isentrop125_bvf2.clim9120.day0121')

**Comment by nicholas512** [comment]
# `.netrc` file
The .netrc file is used by auto-download without input of DIAS account and password.
Create a .netrc file in your home directory as below beforehand.
```
machine data.diasjp.net
login user@example.com（your DIAS account）
password XXXXX
```

**Comment by nicholas512** [comment]
## automating the download

the jumbly url strings are base64-encoded:
```
(base64) L0pSQTNRL0hpc3QvRGFpbHkvYW5sX3N1cmYxMjUvMTk0ODA1L2FubF9zdXJmMTI1LjE5NDgwNTA1MDA
(decoded)  /JRA3Q/History/Daily/anl_surf125/194805/anf_surf125.1948050500
```

**Comment by nicholas512** [comment]
@BinCAO-PF  I've modified the download script to work with python3, if you're interested.  See [this Gist](https://gist.github.com/nicholas512/103f51e7a2c25cc27aef5f2bc227936f)
