### ISSUE TITLE
Wind direction could be greater than 360

### ISSUE THREAD

**Issue by BinCAO-PF** [geocryology/globsim#148]
The scale function for wind direction may lead to a value greater than 360º if both the U and V are negtive. I prose the below scale function, details please see:

https://confluence.ecmwf.int/pages/viewpage.action?pageId=133262398 

WD = np.mod(180 + np.arctan2(U, V) * (180 / np.pi), 360)

**Comment by nicholas512** [comment]
Hi Bin, 

thanks for pointing this out.  
I note both that our current formulation has the arguments reversed for the `atan2` function and that the link you shared says 
> The atan2 arguments vary by type of software and in some applications the arguments (u,v) are switched around. 

I would suggest wrapping the existing calculation in a `modulo 360` . What do you think?

**Comment by BinCAO-PF** [comment]
Hi Nick,
sounds great!
Another function I previously used for other studies was

WD = (270 - (np.degrees(np.arctan2(v, u)) + 360) % 360) % 360

Bests,
BIn
