### ISSUE TITLE
change naming convention for variables in scaled globsim data?

### ISSUE THREAD

**Issue by nicholas512** [geocryology/globsim#28]
Currently, the name of scaled varibles are in the format `{variable type}{reanalysis}{unit}{level}` (e.g. `"PRESS_ERA_Pa_pl"`)

This is somewhat redundant, because of the self-describing nature of netcdf:
* the units should be described in the `units` attribute
* the variable type should be described in the `standard_name` attribute
* the reanalysis could be described in the global attributes

It also causes problems for reading the data: if I want pressure from multiple globsim output files, I can't just read them in and select ['pressure'], I have to build a new string based on whichever reanalysis they came from.

I can see that if there are multiple scaling functions to choose from that were to create multiple instances of the same variable, then it might be helpful to distinguish them by their name, but the current implementation doesn't do this.

I would recommend moving towards removing at least the {reanalysis} and {unit} from the name

@BinCAO-PF and @hgmacc : any thoughts?

![image](https://user-images.githubusercontent.com/15223327/89346804-a7081b00-d677-11ea-8ac4-bb86bd6e2361.png)

**Comment by BinCAO-PF** [comment]
Hi Nick,

I agree to keep the variable name simple and leave the name as {variable type}_{level} (e.g., “PRESS_pl”).

·         the units should be described in the units attribute

> Agree, and we already have the unit attribute for each variable. Note that the unit of temperature variable (e.g., AIRT_ERA5_C_sur and AIRT_ERA5_C_pl) should be revised to ˚C rather than K.

 

·         the variable type should be described in the standard_name attribute

> By removing the reanalysis name and unit, the variable name would be {variable type}_{level} (e.g., “PRESS_pl”). For the standard_name, should we follow the CF standard, and hence become “Air_pressure”? In addition, we still have the variable of long_name: air_pressure ERA-5 pressure levels only. With 1) variable name; 2) standard name; 3) long name, the variable could be well described.

 

·         the reanalysis could be described in the global attributes

> Agree

 

The last comment: should we change ERA-5 to its official name––ERA5 (Please see: https://confluence.ecmwf.int/display/CKB/ERA5%3A+data+documentation; and https://rmets.onlinelibrary.wiley.com/doi/full/10.1002/qj.3803)?

 

 

Bests,

Bin

 

--------

曹斌 博士
特别研究助理
国家青藏高原科学数据中心
青藏高原研究所
中国科学院
北京市朝阳区林萃路16号院


Bin Cao, Ph.D
Research Assistant
National Tibetan Plateau Data Center
Institute of Tibetan Plateau Research (ITP)
Chinese Academy of Sciences (CAS)
No. 16 Lincui Road, Chaoyang District, Beijing 100101, China

Email: bin.cao@itpcas.ac.cn


ORICD: https://orcid.org/0000-0003-2473-2276 

 

Reanalyses & permafrost simulation: https://doi.org/10.5194/gmd-2019-157 

Permafrost simulation: https://doi.org/10.1061/9780784482599.062 

Permafrost mapping: https://doi.org/10.1002/ppp.2006 

Permafrost maps: https://doi.org/10.5194/tc-13-511-2019 

Permafrost thaw subsidence: https://doi.org/10.1029/2018JF004618 

Thermal state of permafrost: https://doi.org/10.1029/2018JD028442 

Surface air temperature downscaling: https://doi.org/10.5194/gmd-10-2905-2017 

Active layer thickness & Geophysics: https://doi.org/10.1002/2016JF004018

**Comment by nicholas512** [comment]
I like the idea of using standard_names rather than arbitrary ones (e.g. "PRESS")

to handle the case where we have the same variable derived from two or more scaling kernels, we should consider the naming convention to be:

`{variable type}_{kernel}`

where `pl` and `sur` are the basic kernels deriving from pressure-level and surface data, respectively. This means we would have

```
air_temperature_pl
air_temperature_sur
air_temperature_redcapp
```

I will change ERA-5 to ERA5 at the same time
