### ISSUE TITLE
Add SH to JRA-55 scaling

### ISSUE THREAD

**Issue by nicholas512** [geocryology/globsim#48]
**Currently**: JRA-55 lacks a scaling kernel for Specific humidity. This may be because it does not download dewpoint temperature (used in calculation of SH for ERA). However, [dewpoint depression](https://en.wikipedia.org/wiki/Dew_point_depression) (T-Td) [exists in the dataset](https://rda.ucar.edu/datasets/ds628.0/#metadata/grib.html?_do=y)  (# 18 / DEPR)
This limits the ability of JRA-55 to be used as an input for certain models, like CLASSIC

**Proposed**:
1. download dew point depression and calculate dew point temperature
2. use dew point temperature to calculate SH using same approach as other reanalyses

**Comment by BinCAO-PF** [comment]
RA-55 reanalysis itself provides specific humidity and is added in GlobSim.

**Comment by nicholas512** [comment]
awesome. I'll close this issue based on the commit at e8fafa9ebe466068e981e2bb9801f54e2bb8d6e7.
