### ISSUE TITLE
Remove unnecessary functions

### ISSUE THREAD

**Issue by BinCAO-PF** [geocryology/globsim#49]
Some functions written very early may not be necessary with the development of GlobSim. Should we consider removing them? I listed two of them below.
Do we still need download functions for ECMWF server since all the data are moved to the cds? Please also note that ECMWF does NOT update ERA-Interim after 31/08/2019.
Do we still need functions to check ESMF? In GlobSim, we've already provided the specific version (7.1.0) of ESMF package ("globsim/lib/esmf-python.tar.gz").

**Comment by nicholas512** [comment]
Hi Bin, good point. I think that both of those can be removed. Maybe we should make it explicit somewhere in the documentation that we only support that version for now.

@hgmacc : are there any functions you've come across that are not used and should be added to this list?

**Comment by BinCAO-PF** [comment]
Thanks Nick,
I removed two functions and related parts.

**Comment by hgmacc** [comment]
Nothing off the top of my head but I'll use this forum if I see anything.

**Comment by nicholas512** [comment]
Closing this as things have largely been cleaned up.
