### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by BinCAO-PF** [geocryology/globsim#60]
Run globsim in docker got the bug below:

_Traceback (most recent call last):
  File "opt/globsim/globsim/globsim_interpolate.py", line 25, in <module>
    from globsim.globsim_main import GlobsimInterpolateStation
ModuleNotFoundError: No module named 'globsim.globsim_main'_

Seems it is raised by switching to absolute imports

**Comment by nicholas512** [comment]
rats, I wanted to make a cleaner command-line interface (2086a06b0be293187bb22d8ff4a8260c2171e04f) , but I guess it wasn't backwards compatible with the previous usage...

To solve this: if you run `python setup.py develop` in the main directory to 'install' globsim, it will add a command-line interface to your system path.  You can then call the command `globsim` from anywhere without having to actually point to the `globsim_download.py` or `globsim_interpolate.py` file.

The new usage is therefore running the following commands from anywhere

`globsim --help`
`globsim download -f file -d JRA`
`globsim interpolate -f file -d 

I assume you got this bug when running `python globsim_download.py ...` ?
