### ISSUE TITLE
Package Install in Dockerfile

### ISSUE THREAD

**Issue by BinCAO-PF** [geocryology/globsim#62]
In the docker file, please think about giving a specified package version for package installation. 
For example, in the released v.1.06, 

> _FROM ubuntu:latest_ 

could be changed to 

>   _FROM ubuntu:18.04_

In this case, the released GlobSim would always use the same version in order to avoid the compatibility issue raised from packages update.

**Comment by nicholas512** [comment]
This is a good point, do you think we need to re-release the _old_ dockerfiles wtih specific versions, or is it sufficient to change the dockerfile moving forward as we release the next major version of globsim?

**Comment by BinCAO-PF** [comment]
It would be sufficient to change the dockerfile in the next released version, and do the same thing in GTPEM. I'll close the issue.

**Comment by nicholas512** [comment]
closed by 23e05b85ded5b16f1412c68ff0819f97c41be487
