### ISSUE TITLE
Interpolation module unable to perform on .nc data subset

### ISSUE THREAD

**Issue by hgmacc** [geocryology/globsim#70]
When performing interpolation, it seems GlobSim is unable to interpolate on a temporal subset. This was attempted using JRA  .nc download files. 

Example: If your .nc file is 2000 - 2010, interpolating 2005-01-01 to 2006-01-01 (a temporal subset) fails. ESMF error reported is: 
`File "/home/hma000/.conda/envs/globsim/lib/python3.6/site-packages/ESMF/util/esmpyarray.py", line 39, in ndarray_from_esmf buffer, order="F")`
`TypeError: buffer is too small for requested array`.

**Comment by nicholas512** [comment]
My interim suspicion of what's going wrong: 
	
* `JRA2station` makes a destination netcdf file with the subsetted dimensions
* `JRA2station` passes interp2D a mixture of subsetted (`tmask_chunk`) and not subsetted (`ncf_in`) data, along with a `None` date parameter
* `interp2d` Ignores the `date` parameter even if it were correct, then makes a source grid and destination grid that are mismatched

**Comment by nicholas512** [comment]
@hgmacc - did you ever get this working?  Was it an input data issue after all?

**Comment by hgmacc** [comment]
Yes, resolved! Was a wonky data issue.
