### ISSUE TITLE
ERA File naming convention broken for Interpolation and Scaling modules

### ISSUE THREAD

**Issue by hgmacc** [geocryology/globsim#75]
Scaling and interpolation are looking for incorrectly named files. This should be refactored throughout the project.

Main issue: `era5_rea_xxx` to `era5_xxx`.

**Comment by nicholas512** [comment]
It looks like you fixed this with commit 34e1724583e06141d633a3e1f1a5c1689ae5717a.  Should this be closed? or does the `rea` come up elsewhere? I wasn't able to find any instances with a code serch on github

**Comment by nicholas512** [comment]
closed by 34e1724583e06141d633a3e1f1a5c1689ae5717a
