### ISSUE TITLE
Branching etiquette - squash or no-squash?

### ISSUE THREAD

**Issue by nicholas512** [geocryology/globsim#78]
Hannah wrote a [nice set of guidelines](https://github.com/geocryology/globsim/wiki/Branching-Etiquette) for the wiki.  Now that there are more people actively working on globsim, I think its worth revisiting this to make sure everyone's on the same page.

In particular, what is everyone's thoughts on squashing vs not squashing 

I've been squashing in the past, but almost got myself into trouble just now because I almost re-merged a branch I had already merged and squashed.  The commits didn't automatically show up as 'in common' with the main branch, so without some digging it wasn't clear that I had already merged (and forgot to delete the old branch).

Any other things we should think of?

@hgmacc @gwib @stgruber

**Comment by hgmacc** [comment]
To-squash or not-to-squash, that is the question. I think this will depend on the reason behind branching. If adding a feature, squashing is nice but should feature a merge request so there's space for a third-party look-over. Thoughts?

**Comment by nicholas512** [comment]
Certainly for non-trivial code changes, I think merge requests and some review will be the way to go (but perhaps with a time limit on how long they sit around for before they get implicit/automatic approval in case everyone's busy ).

One concern I have with squashing, even for features, is that we don't yet have a good way to test the code. So once something is committed to `main`, it might be hard to identify which commit has the problem if they're all bundled together.  If we can work out some better tests (I have a few ideas for this) then I'd be open to squashing, but at the moment I'm leaning more towards not-squashing.
